### ISSUE TITLE
fatal error C1083:

### ISSUE THREAD

**Issue by diet-teacher** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#12]
hellow @JustasBart 
i was trying to build your code with visual studio 2017 
But the C1083: error occurred. it said "'getopt.h': No such file or directory"
i did install getopt.h file from 'exefile.com' but result was same.
Didn't you have this problem?

**Comment by JustasBart** [comment]
Hi @diet-teacher I haven't seen anything like this before, but to me it sounds like there might be something missing or wrong with your OpenCVs installation.

Please refer to:
![238269073-71a884ee-3ef6-4853-9531-7fd005e6d0e9](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/40023722/a57d40e8-26d2-44cf-9a05-cea18269136c)

And if possible perhaps rebuilt your OpenCV. Mind you I've only really done any of this on Linux and so this could be a Windows specific thing as well - I wouldn't know. But if you're able to build it from source with the above instructions then in theory you should know if that was the case or not.

Sorry but I can't really help you out further at this point, try and mess around with it and let me know how you get on.

All the best to you and good luck! 🚀

**Comment by diet-teacher** [comment]
thank you for your response.
I'm gonna start working on monday.
I'll let you know what was the problem when I find a way.
thank you.

**Comment by JustasBart** [comment]
@diet-teacher Did you resolve this issue in the end?

**Comment by JustasBart** [comment]
Closing this for now, feel free to re-open if you've any more information etc...

**Comment by diet-teacher** [comment]
i solved this problem with rebuilding opencv and erasing #include <getopt.h>.
I'm sorry to have kept you waiting for an response.
thank you!
