### ISSUE TITLE
With the same code content, the yolov5s.onnx model you provided can run normally, but the yolov8s.onnx model runs incorrectly.

### ISSUE THREAD

**Issue by 7288Fzq** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#13]
Here is the result of running the yolov5s.onnx model, it succeeded.
![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/71710433/59183c6c-662e-42b0-9d2c-66ed2c3691a6)
![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/71710433/9366295d-49b1-4368-bee8-cbfa0480cca4)
Please note! I did not modify any part of the code except this part in main.cpp.![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/71710433/c9fb9c4b-cd42-4306-af49-929a4bc0f966)
After I changed it to your sources/models/yolov8s.onnx, after recompiling, the following problems occurred:
![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/71710433/15ed1f4e-091b-49ff-b514-5c929b53246a)
I am now wondering whether it is a problem of divergence in the reasoning of these two models in your code

**Comment by 7288Fzq** [comment]
I hope you have a little impression of me, because I asked almost the same question before, and I didn't use the yolov5s model for testing. Now that I've regained interest in your project, I've discovered that the problem may be on a different model. ：）

**Comment by 7288Fzq** [comment]
hey，I noticed that even when yolov5s.onnx runs successfully, the console still prompts some errors.
![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/71710433/9fd5e6e2-77fc-415b-a1ca-af949ec5beeb)

**Comment by JustasBart** [comment]
Hi @7288Fzq and sorry for my absence from this. First of all did you figure this issue out by now?
Second of all if you haven't you should note that the yolov8 models need to be transposed before running inference, therefore, I wonder does your build fully support all of the OpenCV functionalities in order to achieve this?

**Comment by JustasBart** [comment]
I'll close this for now...
