### ISSUE TITLE
Can't detect the objects in release mode using CPU device

### ISSUE THREAD

**Issue by jow905** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#14]
Hi, @JustasBart 
I test the code and found issue when compiling the code in RELEASE mode , I change "bool runOnGPU = **false;**" , no objects were detected in picture 'bus.jpg' using yolov8s.onnx and just one object was detected in yolov5s.onnx.
But in DEBUG mode all objects were detected perfectly!! 

yolov8s.onnx
![yolov8s_onnx](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/19189198/94e69417-1b4f-4e76-802c-dffa62be69cd)

yolov5s.onnx
![yolov5s_onnx](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/19189198/a779c561-31a2-4d92-9ffc-3d92160a14d2)

I compile opencv4.7 from source following this:
![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/19189198/9872a0ee-1f5e-460b-b731-f01375be23cb)

PC Environment:
  -Windows11 Pro 64bit
  -CUDA11.6.2
  -CUDNN8.4.1
  -Vistual Studio 2022 Enterprise
  -OpenCV4.7 with cuda
  -Qt5.15.9

Could you give some advise on the issue? thanks!

**Comment by JustasBart** [comment]
Hi @jow905 to be honest with you I wouldn't really know what's going wrong with that... It's odd that the code builds and runs but that the actual outputs aren't too healthy... Overall I think that this is an OpenCV build issue (But like you've said you have it all cleanly built etc...) do note that @TheYoungBeast has recently pointed out that the flag '**OPENCV_DNN_CUDA**' is missing on the chart,,, I wonder could that possibly resolve this?

**Comment by jow905** [comment]
Yes, I already set the flag" OPENCV_DNN_CUDA" when I compiled OpenCV 3 times cleanly from source and also get the same result, but I found when I use yolov8m.pt and convert it to onnx format and try again, it works perfectly in both debug and release mode. 
the command convert the model:
 
```shell
yolo export model=yolov8m.pt format=onnx imgsz=640,480 opset=12
``` 

 I think maybe I need to try change something of my PC environment, such as the version of cuda , cudnn.

![image](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/assets/19189198/f7eb5e45-481c-4c3a-a36f-6e5745b8bca3)

**Comment by JustasBart** [comment]
@jow905 That's a rather interesting find, yes, I do wonder if exporting a model from **.pt** to **.onnx** is different along with a different CUDA setup or any other parameter such as the OS and whatnot... You might be onto something here...

But just to confirm so if you export your own model then it seemingly works whereas if you run the sample included model then it doesn't?

**Comment by JustasBart** [comment]
I'll close this for now...
