### ISSUE TITLE
vector subscript out of range

### ISSUE THREAD

**Issue by ws-researcher** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#3]
There is a error when I run it. 
![1677259299](https://user-images.githubusercontent.com/50359672/221246094-d1b5139f-6606-4183-b612-5e513aadf44e.jpg)

**Comment by JustasBart** [comment]
Hi @ws-researcher I can see that you are running the OpenCV World build. As far as I know the World build is not really recommended for a lot of reasons and I would highly suggest not using it especially for something like running Inference, however I also haven't tried doing absolutely anything on a World based build (For the same reason) so I couldn't really tell what is wrong. The one thing that I can offer you is this diagram:

![OpenCV build](https://user-images.githubusercontent.com/40023722/221406323-217f0ed8-82e8-42b5-9006-85af433f040e.png)

outlining the flags/setup of how OpenCV should be built in order for this Inference code to run however once again I couldn't say if this would work on a World based build or not.

Anything outside of this I'm afraid you'll have to try and Google your way out of it, but before you do, have you tried running on the CPU as well as the GPU?

Good luck! :rocket:

**Comment by JustasBart** [comment]
@ws-researcher Is it okay with you if I close this issue? Or do you have any follow-up questions/inputs on this?
