### ISSUE TITLE
Yolov8 Segment

### ISSUE THREAD

**Issue by chchienGH** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#5]
Does this code work for Yolov8 instance segmentation?   Or there is another version for instance segmentation available?  Thanks.

**Comment by JustasBart** [comment]
Hi @chchienGH no, unfortunately the Instance Segmentation is a whole other beast that I haven't had the chance to figure out yet, though you might get lucky to find some examples elsewhere but none that I've tried personally...

Good luck! :rocket:
