### ISSUE TITLE
libtorch version of cpp inference

### ISSUE THREAD

**Issue by SuperGentry** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#6]
Hi, is there a libtorch version of cpp inference. If it is not too different from that version which should be better to change from? Looking forward to your reply.

**Comment by JustasBart** [comment]
Hi @SuperGentry I've never tried using the **PyTorch C++ API** so no, I haven't a clue as per what's involved in that, though I've seen examples of running yolov8 with **ONNX Runtime** if that's of any use for you at all...

In theory though this example should at least help explain how to parse the output of the model and thus that might be useful when wrapping that in **PyTorch**?

Good luck! :rocket:
