### ISSUE TITLE
Inference failed running Yolov8CPPInference failed

### ISSUE THREAD

**Issue by Zhaonb** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#7]
Environment:
VMware® Workstation 15 Pro+ubuntu18.04
OpenCV(4.6.0)
!CUDA

obt@ubuntu:~/workspace/NNF/yolov8_CPP_Inference_OpenCV_ONNX/build$ ./Yolov8CPPInference 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/obt/workspace/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:255: error: (-5:Bad argument) Can't read ONNX file: /home/.../yolov8_CPP_Inference_OpenCV_ONNX/source/models/yolov8s.onnx in function 'ONNXImporter'

Aborted (core dumped)

**Comment by Zhaonb** [comment]
Edit the main.cpp to change the projectBasePath to match your user.

**Comment by JustasBart** [comment]
@Zhaonb I'm glad you were able to resolve it, all the best! :rocket:
