### ISSUE TITLE
Issue running example

### ISSUE THREAD

**Issue by stevedanomodolor** [JustasBart/yolov8_CPP_Inference_OpenCV_ONNX#9]
When I try to run the example, I get this error. 
Running on CUDA
[ WARN:0] global ./modules/dnn/src/dnn.cpp (1447) setUpNet DNN module was not built with CUDA backend; switching to CPU
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) ./modules/dnn/include/opencv2/dnn/shape_utils.hpp:170: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'total'

Aborted (core dumped)

**Comment by stevedanomodolor** [comment]
Solved, update to 4.7.0

**Comment by JustasBart** [comment]
@stevedanomodolor That's good to hear! The older versions of OpenCV had the (**NGRAP** and **INF_ENGINE**) flags that could've been it or perhaps some other flag/issue, I'm glad you've been able to resolve this.
